name: comfy_app

on: push

jobs: 
  comfy_app:
    name: Lint code base
    runs-on: ubuntu-latest
    steps: 
      - names: Checkout code
        uses: actions/checkout@v2

      -name: Run comfy_app
       uses: github/comfy_app@v3
       env: 
          DEFAULT_BRANCH: main
          GITHUB TOKEN: ${{ secrets.GITHUB TOKEN }}